### ISSUE TITLE
Sentry is not working

### ISSUE THREAD

**Issue by s1gr1d** [getsentry/sentry-sdk-browser-extension#2]
Help I just installed the Sentry SDK and it is not working.

**Comment by mydea** [comment]
Hello, thank you for writing in! Could you provide me with more information about your setup?

**Comment by s1gr1d** [comment]
I am using the latest version for sure, I did everything correctly but nothing works, please help. My website is http://works-on-my-machine.com/ and Sentry is not sending any data there.

**Comment by s1gr1d** [comment]
Sure, this is my code:

```jsx
setupApp();
setupSentry({ enabled: true });
```

but nothing is working please help.
